Feature: Fetching Identify parameters before harvesting ( if HARVESTI…
lareferencia/lareferencia-core-lib pull request #4
Opened 2022-10-11 13:47 UTC by lareferencia

…NG_IDENTIFY_PARAMETERS == TRUE )

This one solves issue  #3

Please note that lrharvester app must be updated in order to have the HARVESTING_IDENTIFY_PARAMETERS option in the UI

![image](https://user-images.githubusercontent.com/3843375/195108338-73cf0c56-48a2-4596-99f5-ac3be630ab06.png)

@paulo-graca Please test

2022-10-13 13:31 UTC, paulo-graca commented
Thank you @lmatas I will try it out and let you know!

2022-10-13 15:26 UTC, paulo-graca reviewed
This feature worked for us, but, as is, present us an usability challenge.
I think we should look into `HarvestingWorker` in a different perspective. Currently we need to set all the settings we need to activate for the harvesting. We are looking to this feature as an developer when we want to only address specific stuff, to have the must optimized process as possible.
But, for a new user, technical or not, this is difficult to achieve. I think we should address them differently. As a always active settings, letting the featured and skilled user to fine tune and disable what he don't need for that particular network, disabling it.

Saying this, I think we can have a new setting to control the Identify access, but be always active by default. I also think we should do this to all other settings in this Worker, leaving us to  only "activate" what we don't want. Meaning all settings should be renamed to a inverse, contrary or negative naming, also changing the logic in the worker.

2022-10-13 15:26 UTC, paulo-graca commented on src/main/java/org/lareferencia/core/harvester/workers/HarvestingWorker.java
> +		if ( runningContext.getNetwork().getBooleanPropertyValue("HARVEST_IDENTIFY_PARAMETERS") ) {
Does this makes sense? You are given the admin user the responsability to understand how the OAI of the repository works and add this setting on a different screen, you are creating an usability issue, the person when defining the OAI, must also remember to go to a different screen to check the required configuration. I don't think it's very praticle, when, like us, you have more than 400 resources.

2022-10-19 09:35 UTC, paulo-graca requested changes
I did another test and an error still occurs with incremental harvesting:


```
2022-10-19 10:32:09.848  INFO 50732 --- [nio-8090-exec-2] o.l.b.controllers.ActionsController      : HARVESTING_ACTION:: incremental:true :: network: scielopt(id:452)
2022-10-19 10:32:10.656  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : Identify Granularity found: YYYY-MM-DD
2022-10-19 10:32:10.669  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : scielopt(id:452) Starting incremental harvesting from date: 2022-10-19T09:59:30Z -- Snapshot: 23542
2022-10-19 10:32:10.675  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : Harvesting is starting for scielopt(id:452)...
2022-10-19 10:32:10.690  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : There aren't defined sets. Harvesting the entire collection for scielopt(id:452)
2022-10-19 10:32:10.711 ERROR 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : Fatal Error:ListRecords call error :: error code: badArgument
2022-10-19 10:32:10.730 ERROR 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : scielopt(id:452) :: Harvesting ended with errors !!!

```

2022-10-19 09:38 UTC, lmatas commented
Question:
Do you know if Scielo supports incremental harvesting??
Lautaro Matas


El mié, 19 oct 2022 a las 11:35, Paulo Graça ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> I did another test and an error still occurs with incremental harvesting:
>
> 2022-10-19 10:32:09.848  INFO 50732 --- [nio-8090-exec-2] o.l.b.controllers.ActionsController      : HARVESTING_ACTION:: incremental:true :: network: scielopt(id:452)
> 2022-10-19 10:32:10.656  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : Identify Granularity found: YYYY-MM-DD
> 2022-10-19 10:32:10.669  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : scielopt(id:452) Starting incremental harvesting from date: 2022-10-19T09:59:30Z -- Snapshot: 23542
> 2022-10-19 10:32:10.675  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : Harvesting is starting for scielopt(id:452)...
> 2022-10-19 10:32:10.690  INFO 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : There aren't defined sets. Harvesting the entire collection for scielopt(id:452)
> 2022-10-19 10:32:10.711 ERROR 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : Fatal Error:ListRecords call error :: error code: badArgument
> 2022-10-19 10:32:10.730 ERROR 50732 --- [askScheduler-10] o.l.c.h.workers.HarvestingWorker         : scielopt(id:452) :: Harvesting ended with errors !!!
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lareferencia/lareferencia-core-lib/pull/4#pullrequestreview-1147198928>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH7G6V7JSAR65GHOIBNYKLWD66GTANCNFSM6AAAAAARCJ2PWI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-19 09:46 UTC, paulo-graca commented
Yes. It supports. The request was made still ignoring the granularity:

```
2022-10-19 10:42:13.562 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : requestURL=https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
2022-10-19 10:42:13.562 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : try:0 getting requestURL: https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
2022-10-19 10:42:13.598 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc responseCode=200
2022-10-19 10:42:13.598 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : contentEncoding=null

```

This doesn't work:
https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc

but this does:
https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19&metadataPrefix=oai_dc

2022-10-19 09:47 UTC, lmatas commented
Ok, I will test with this exact case and let you know.
Lautaro Matas


El mié, 19 oct 2022 a las 11:46, Paulo Graça ***@***.***>)
escribió:

> Yes. It supports. The request was made still ignoring the granularity:
>
> 2022-10-19 10:42:13.562 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : requestURL=https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
> 2022-10-19 <https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc2022-10-19> 10:42:13.562 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : try:0 getting requestURL: https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
> 2022-10-19 <https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc2022-10-19> 10:42:13.598 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc responseCode=200
> 2022-10-19 10:42:13.598 DEBUG 58080 --- [taskScheduler-3] o.o.oai.harvester2.verb.HarvesterVerb    : contentEncoding=null
>
>
> This doesn't work:
>
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
>
> but this does:
>
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19&metadataPrefix=oai_dc
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lareferencia/lareferencia-core-lib/pull/4#issuecomment-1283725788>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH7G6QIAVYAOXYEARDCUD3WD67OPANCNFSM6AAAAAARCJ2PWI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-19 10:27 UTC, lareferencia commented
***@***.*** The problem was a missing granularity case, I didn't
consider the case sensitive issue on the first implementation. Now I think
that will work, please test. *

Lautaro Matas


El mié, 19 oct 2022 a las 11:48, Lautaro Matas ***@***.***>)
escribió:

> Ok, I will test with this exact case and let you know.
> Lautaro Matas
>
>
> El mié, 19 oct 2022 a las 11:46, Paulo Graça ***@***.***>)
> escribió:
>
> > Yes. It supports. The request was made still ignoring the granularity:
> >
> > 2022-10-19 10:42:13.562 DEBUG 58080 --- [taskScheduler-3]
> o.o.oai.harvester2.verb.HarvesterVerb : requestURL=
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
> > 2022-10-19 <
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc2022-10-19>
> 10:42:13.562 DEBUG 58080 --- [taskScheduler-3]
> o.o.oai.harvester2.verb.HarvesterVerb : try:0 getting requestURL:
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
> > 2022-10-19 <
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc2022-10-19>
> 10:42:13.598 DEBUG 58080 --- [taskScheduler-3]
> o.o.oai.harvester2.verb.HarvesterVerb :
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
> responseCode=200
> > 2022-10-19 10:42:13.598 DEBUG 58080 --- [taskScheduler-3]
> o.o.oai.harvester2.verb.HarvesterVerb : contentEncoding=null
> >
> >
> > This doesn't work:
> >
> >
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19T09:58:26Z&metadataPrefix=oai_dc
> >
> > but this does:
> >
> >
> https://www.scielo.pt/oai/scielo-oai.php?verb=ListRecords&from=2022-10-19&metadataPrefix=oai_dc
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/lareferencia/lareferencia-core-lib/pull/4#issuecomment-1283725788
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAH7G6QIAVYAOXYEARDCUD3WD67OPANCNFSM6AAAAAARCJ2PWI
> >
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lareferencia/lareferencia-core-lib/pull/4#issuecomment-1283728004>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA5KKL3R6XC7SQ3IKHNS4Y3WD67VPANCNFSM6AAAAAARCJ2PWI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-19 15:05 UTC, paulo-graca approved these changes
Now it works as expected.

2022-10-19 15:05 UTC, merged